services:
  apache:
    image: php:8.1-apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`php.dev.tvoelkner.de`) && PathPrefix('/praefix)"
      - "traefik.http.middlewares.strip-testpath.stripprefix.prefixes=/praefix"
      - "traefik.http.routers.apache.middlewares=strip-testpath@docker"
    networks:
      - traefik_web
    volumes:
      - ./html:/var/www/html

networks:
  traefik_web:
    external: true