services:
  apache:
    image: php:8.1-apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`php.docker.tvoelkner.de`)"
    networks:
      - traefik_web
    volumes:
      - ./html:/var/www/html

networks:
  traefik_web:
    external: true