services:
  nginx:
    image: nginx:1.20
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`app2.germanywestcentral.cloudapp.azure.com`)"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true